### ISSUE TITLE
(C3D-inception-lstm) Hasani and Mahoor (Facial Expression Recognition Using Enhanced Deep 3D Convolutional Neural Networks)

### ISSUE THREAD

**Issue by so77id** [so77id/deep-learning-reviews#12]
### Paper
[Facial Expression Recognition Using Enhanced Deep 3D Convolutional Neural Networks](https://arxiv.org/abs/1705.07871)

### Related
* [ ] Shan et. al. [Facial expression recognition based on local binary patterns: A comprehensive study](http://www.sciencedirect.com/science/article/pii/S0262885608001844)
* [ ] Y. Tian, T. Kanade, and J. F. Cohn. Recognizing lower face action units for facial expression analysis.
* [ ] **(FER)** A. Mollahosseini, B. Hasani, M. J. Salvador, H. Abdollahi, D. Chan, and M. H. Mahoor. Facial expression recognition from world wild web.
* [ ] E. Sariyanidi et. al. Automatic anal- ysis of facial affect: A survey of registration, representation, and recognition.
* [ ] (GoogLeNet #6) C. Szegedy et. al. [Going deeper with convolutions](https://arxiv.org/pdf/1409.4842.pdf)
* [ ] #7 A.Mollahosseini et. al. [Going deeper in facial expression recognition using deep neural networks.](https://arxiv.org/pdf/1511.04110.pdf)
* [ ] A.Mollahosseini et. al Facial expression recognition from world wild web.
* [ ]  K. He et. el [Deep residual learning for image recognition](https://arxiv.org/pdf/1512.03385.pdf)
* [ ] P. Molchanov, X. Yang, S. Gupta, K. Kim, S. Tyree, and J. Kautz. Online detection and classification of dynamic hand gestures with recurrent 3d convolutional neural network.
* [ ] (EmotiW 2016 Winner) Y. Fan et. al. Video-based emotion recognition using cnn-rnn and c3d hybrid networks. [Paper](https://github.com/so77id/deep-learning-reviews/files/1175619/cnn-rnn.c3d.pdf)
* [ ] J. Donahue et. al. Long-term recurrent convolutional networks for visual recognition and description.
* [ ] **(FER)** B. Hasani and M. H. Mahoor. Spatio-temporal facial expression recognition using convolutional neural networks and conditional random fields
* [ ] (Inception-v4 #11) C. Szegedy. et. al. [inception-resnet and the impact of residual connections on learning.](https://arxiv.org/pdf/1602.07261.pdf)
* [ ] ADD state of art methods
